# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/p4wifi/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries

PRODUCT_COPY_FILES := \
    vendor/samsung/p4wifi/proprietary/bin/glgps:system/bin/glgps \
    vendor/samsung/p4wifi/proprietary/bin/gps.cer:system/bin/gps.cer \
    vendor/samsung/p4wifi/proprietary/bin/tegrastats:system/bin/tegrastats \
    vendor/samsung/p4wifi/proprietary/etc/audio/Rx_ControlParams_BLUETOOTH_HEADSET.txt:system/etc/audio/Rx_ControlParams_BLUETOOTH_HEADSET.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/Tx_ControlParams_BLUETOOTH_HEADSET.txt:system/etc/audio/Tx_ControlParams_BLUETOOTH_HEADSET.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/LVVEFS_Rx_Configuration.txt:system/etc/audio/LVVEFS_Rx_Configuration.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/LVVEFS_Tx_Configuration.txt:system/etc/audio/LVVEFS_Tx_Configuration.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/Rx_ControlParams_EARPIECE_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_EARPIECE_WIDEBAND.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/Rx_ControlParams_SPEAKER_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_SPEAKER_WIDEBAND.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/Rx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/Rx_ControlParams_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_WIRED_HEADSET_WIDEBAND.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/Tx_ControlParams_EARPIECE_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_EARPIECE_WIDEBAND.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/Tx_ControlParams_SPEAKER_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_SPEAKER_WIDEBAND.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/Tx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/Tx_ControlParams_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_WIRED_HEADSET_WIDEBAND.txt \
    vendor/samsung/p4wifi/proprietary/etc/firmware/bcm4330B1.hcd:system/etc/firmware/bcm4330B1.hcd \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_aacdec.axf:system/etc/firmware/nvmm_aacdec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_adtsdec.axf:system/etc/firmware/nvmm_adtsdec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_h264dec.axf:system/etc/firmware/nvmm_h264dec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_h264dec2x.axf:system/etc/firmware/nvmm_h264dec2x.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_jpegdec.axf:system/etc/firmware/nvmm_jpegdec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_jpegenc.axf:system/etc/firmware/nvmm_jpegenc.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_manager.axf:system/etc/firmware/nvmm_manager.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_mp3dec.axf:system/etc/firmware/nvmm_mp3dec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_mpeg4dec.axf:system/etc/firmware/nvmm_mpeg4dec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_service.axf:system/etc/firmware/nvmm_service.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_vc1dec.axf:system/etc/firmware/nvmm_vc1dec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_wavdec.axf:system/etc/firmware/nvmm_wavdec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_wmadec.axf:system/etc/firmware/nvmm_wmadec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_wmaprodec.axf:system/etc/firmware/nvmm_wmaprodec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvrm_avp.bin:system/etc/firmware/nvrm_avp.bin \
    vendor/samsung/p4wifi/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/p4wifi/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/p4wifi/proprietary/etc/wifi/wl:system/etc/wifi/wl \
    vendor/samsung/p4wifi/proprietary/vendor/lib/egl/libEGL_tegra.so:system/vendor/lib/egl/libEGL_tegra.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/egl/libGLESv1_CM_tegra.so:system/vendor/lib/egl/libGLESv1_CM_tegra.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/egl/libGLESv2_tegra.so:system/vendor/lib/egl/libGLESv2_tegra.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/hw/audio.primary_vendor.tegra.so:system/vendor/lib/hw/audio.primary_vendor.tegra.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/hw/audio_policy.vendor.tegra.so:system/vendor/lib/hw/audio_policy.vendor.tegra.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/hw/camera.vendor.tegra.so:system/vendor/lib/hw/camera.vendor.tegra.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/hw/gps.tegra.so:system/vendor/lib/hw/gps.tegra.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/hw/gralloc.tegra.so:system/vendor/lib/hw/gralloc.tegra.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/hw/hwcomposer.tegra_v0.so:system/vendor/lib/hw/hwcomposer.tegra_v0.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/hw/lights.p3.so:system/vendor/lib/hw/lights.p3.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/hw/sensors.p3.so:system/vendor/lib/hw/sensors.p3.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/lib_Samsung_Resampler.so:system/vendor/lib/lib_Samsung_Resampler.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libakm.so:system/vendor/lib/libakm.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libardrv_dynamic.so:system/vendor/lib/libardrv_dynamic.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libcgdrv.so:system/vendor/lib/libcgdrv.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/liblvvefs.so:system/vendor/lib/liblvvefs.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libmllite.so:system/vendor/lib/libmllite.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libmlplatform.so:system/vendor/lib/libmlplatform.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libmpl.so:system/vendor/lib/libmpl.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvapputil.so:system/vendor/lib/libnvapputil.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvasfparserhal.so:system/vendor/lib/libnvasfparserhal.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvaviparserhal.so:system/vendor/lib/libnvaviparserhal.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvavp.so:system/vendor/lib/libnvavp.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvcamerahdr.so:system/vendor/lib/libnvcamerahdr.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvcontrol_jni.so:system/vendor/lib/libnvcontrol_jni.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvcpud_client.so:system/vendor/lib/libnvcpud_client.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvcpud.so:system/vendor/lib/libnvcpud.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvddk_2d.so:system/vendor/lib/libnvddk_2d.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvddk_2d_v2.so:system/vendor/lib/libnvddk_2d_v2.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmm_asfparser.so:system/vendor/lib/libnvmm_asfparser.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmm_audio.so:system/vendor/lib/libnvmm_audio.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmm_aviparser.so:system/vendor/lib/libnvmm_aviparser.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmm_camera.so:system/vendor/lib/libnvmm_camera.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmm_contentpipe.so:system/vendor/lib/libnvmm_contentpipe.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmm_image.so:system/vendor/lib/libnvmm_image.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmmlite_audio.so:system/vendor/lib/libnvmmlite_audio.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmmlite.so:system/vendor/lib/libnvmmlite.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmmlite_utils.so:system/vendor/lib/libnvmmlite_utils.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmmlite_video.so:system/vendor/lib/libnvmmlite_video.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmm_manager.so:system/vendor/lib/libnvmm_manager.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmm_msaudio.so:system/vendor/lib/libnvmm_msaudio.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmm_parser.so:system/vendor/lib/libnvmm_parser.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmm_service.so:system/vendor/lib/libnvmm_service.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmm.so:system/vendor/lib/libnvmm.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmm_utils.so:system/vendor/lib/libnvmm_utils.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmm_vc1_video.so:system/vendor/lib/libnvmm_vc1_video.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmm_video.so:system/vendor/lib/libnvmm_video.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvmm_writer.so:system/vendor/lib/libnvmm_writer.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvodm_dtvtuner.so:system/vendor/lib/libnvodm_dtvtuner.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvodm_hdmi.so:system/vendor/lib/libnvodm_hdmi.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvodm_imager.so:system/vendor/lib/libnvodm_imager.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvodm_misc.so:system/vendor/lib/libnvodm_misc.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvodm_query.so:system/vendor/lib/libnvodm_query.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvomxadaptor.so:system/vendor/lib/libnvomxadaptor.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvomxilclient.so:system/vendor/lib/libnvomxilclient.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvomx.so:system/vendor/lib/libnvomx.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvparser.so:system/vendor/lib/libnvparser.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvrm_graphics.so:system/vendor/lib/libnvrm_graphics.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvrm.so:system/vendor/lib/libnvrm.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvsm.so:system/vendor/lib/libnvsm.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvtestio.so:system/vendor/lib/libnvtestio.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvtestresults.so:system/vendor/lib/libnvtestresults.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvtvmr.so:system/vendor/lib/libnvtvmr.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvwinsys.so:system/vendor/lib/libnvwinsys.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libnvwsi.so:system/vendor/lib/libnvwsi.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libsec-ril-apalone.so:system/vendor/lib/libsec-ril-apalone.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libsecril-client.so:system/vendor/lib/libsecril-client.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libwvm.so:system/vendor/libwvm.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/libWVStreamControlAPI_L3.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/libwvdrm_L3.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/mediadrm/libwvdrmengine.so \
    vendor/samsung/p4wifi/proprietary/vendor/lib/omxplayer.so:system/vendor/lib/omxplayer.so \
    vendor/samsung/p4wifi/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
    vendor/samsung/p4wifi/proprietary/usr/share/alsa/cards/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
    vendor/samsung/p4wifi/proprietary/usr/share/alsa/pcm/center_lfe.conf:system/usr/share/alsa/pcm/center_lfe.conf \
    vendor/samsung/p4wifi/proprietary/usr/share/alsa/pcm/default.conf:system/usr/share/alsa/pcm/default.conf \
    vendor/samsung/p4wifi/proprietary/usr/share/alsa/pcm/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
    vendor/samsung/p4wifi/proprietary/usr/share/alsa/pcm/dpl.conf:system/usr/share/alsa/pcm/dpl.conf \
    vendor/samsung/p4wifi/proprietary/usr/share/alsa/pcm/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
    vendor/samsung/p4wifi/proprietary/usr/share/alsa/pcm/front.conf:system/usr/share/alsa/pcm/front.conf \
    vendor/samsung/p4wifi/proprietary/usr/share/alsa/pcm/iec958.conf:system/usr/share/alsa/pcm/iec958.conf \
    vendor/samsung/p4wifi/proprietary/usr/share/alsa/pcm/modem.conf:system/usr/share/alsa/pcm/modem.conf \
    vendor/samsung/p4wifi/proprietary/usr/share/alsa/pcm/rear.conf:system/usr/share/alsa/pcm/rear.conf \
    vendor/samsung/p4wifi/proprietary/usr/share/alsa/pcm/side.conf:system/usr/share/alsa/pcm/side.conf \
    vendor/samsung/p4wifi/proprietary/usr/share/alsa/pcm/surround40.conf:system/usr/share/alsa/pcm/surround40.conf \
    vendor/samsung/p4wifi/proprietary/usr/share/alsa/pcm/surround41.conf:system/usr/share/alsa/pcm/surround41.conf \
    vendor/samsung/p4wifi/proprietary/usr/share/alsa/pcm/surround50.conf:system/usr/share/alsa/pcm/surround50.conf \
    vendor/samsung/p4wifi/proprietary/usr/share/alsa/pcm/surround51.conf:system/usr/share/alsa/pcm/surround51.conf \
    vendor/samsung/p4wifi/proprietary/usr/share/alsa/pcm/surround71.conf:system/usr/share/alsa/pcm/surround71.conf
